// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompositeLabels() {
  return window['go']['main']['App']['CompositeLabels']();
}

export function GetHeaders(arg1) {
  return window['go']['main']['App']['GetHeaders'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SetColumns(arg1, arg2) {
  return window['go']['main']['App']['SetColumns'](arg1, arg2);
}

export function SetLayout(arg1) {
  return window['go']['main']['App']['SetLayout'](arg1);
}

export function SetSaveLocation() {
  return window['go']['main']['App']['SetSaveLocation']();
}
