// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {excel} from '../models';
import {main} from '../models';

export function CompositeLabels():Promise<void>;

export function GetHeaders(arg1:number):Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function SelectFile():Promise<excel.LabelInfo>;

export function SetColumns(arg1:string,arg2:string):Promise<void>;

export function SetLayout(arg1:main.Layout):Promise<void>;
