// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {excel} from '../models';

export function GetHeaders(arg1:number):Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;

export function SelectFile():Promise<excel.LabelInfo>;
